# Generated by Django 5.1.3 on 2025-01-12 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': [('mailing_permission', 'mailing pemission'), ('disabling_users', 'disabling users'), ('disabling_mailing', 'disabling mailing')], 'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
    ]
