# Generated by Django 5.1.3 on 2025-01-02 23:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MailingRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('full_name', models.CharField(max_length=100)),
                ('comment', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_message', models.CharField(max_length=100)),
                ('body_message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Mailout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datime_first_sending', models.DateTimeField()),
                ('datime_end_sending', models.DateTimeField()),
                ('status_mailing', models.CharField(choices=[('created', 'создана'), ('launch', 'запущена'), ('completed', 'завершена')], default='created', max_length=9, verbose_name='статус рассылки')),
                ('recipient', models.ManyToManyField(to='mailing.mailingrecipient')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailing.message')),
            ],
        ),
        migrations.CreateModel(
            name='AttemptToSend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_attempt', models.CharField(choices=[('successfully', 'успешно'), ('not successful', 'не успешно')], default='not successful', max_length=14)),
                ('mailing_server_response', models.TextField()),
                ('mailout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailing.mailout')),
            ],
        ),
    ]
