# Generated by Django 5.1.3 on 2025-01-08 04:05

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attempttosend',
            options={'verbose_name': 'Попытка рассылки', 'verbose_name_plural': 'Попытки рассылки'},
        ),
        migrations.AlterModelOptions(
            name='mailingrecipient',
            options={'verbose_name': 'Получатель', 'verbose_name_plural': 'Получатели'},
        ),
        migrations.AlterModelOptions(
            name='mailout',
            options={'verbose_name': 'Рассылка', 'verbose_name_plural': 'Рассылки'},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'verbose_name': 'Сообщение', 'verbose_name_plural': 'Сообщения'},
        ),
        migrations.AddField(
            model_name='attempttosend',
            name='datime_attempt',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attempttosend',
            name='mailing_server_response',
            field=models.TextField(verbose_name='ответ почтового сервера'),
        ),
        migrations.AlterField(
            model_name='attempttosend',
            name='mailout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailing.mailout', verbose_name='рассылка'),
        ),
        migrations.AlterField(
            model_name='attempttosend',
            name='status_attempt',
            field=models.CharField(choices=[('successfully', 'успешно'), ('not successful', 'не успешно')], default='not successful', max_length=14, verbose_name='статус рассылки'),
        ),
        migrations.AlterField(
            model_name='mailingrecipient',
            name='comment',
            field=models.TextField(verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='mailingrecipient',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='mailingrecipient',
            name='full_name',
            field=models.CharField(max_length=100, verbose_name='Имя клиента'),
        ),
        migrations.AlterField(
            model_name='mailout',
            name='datime_end_sending',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mailout',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailing.message', verbose_name='Сообщение'),
        ),
        migrations.AlterField(
            model_name='mailout',
            name='recipient',
            field=models.ManyToManyField(to='mailing.mailingrecipient', verbose_name='Получатели'),
        ),
        migrations.AlterField(
            model_name='message',
            name='body_message',
            field=models.TextField(verbose_name='Текст сообщения'),
        ),
        migrations.AlterField(
            model_name='message',
            name='subject_message',
            field=models.CharField(max_length=100, verbose_name='Тема письма'),
        ),
    ]
