# Generated by Django 5.1.3 on 2025-01-09 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0002_alter_attempttosend_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailout',
            name='datime_end_sending',
            field=models.DateTimeField(blank=True, null=True, verbose_name='дата и время последней отправки'),
        ),
        migrations.AlterField(
            model_name='mailout',
            name='datime_first_sending',
            field=models.DateTimeField(verbose_name='дата и время первой отправки'),
        ),
    ]
