# Generated by Django 5.1.3 on 2025-01-10 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0004_attempttosend_ownership_mailingrecipient_ownership_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attempttosend',
            name='ownership',
        ),
    ]
